# Generated by Django 3.2.18 on 2023-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('email', models.EmailField(max_length=150)),
                ('tipo_servicio', models.IntegerField(choices=[(1, 'Internet 300'), (2, 'Internet 500'), (3, 'Internet 1000'), (4, 'Pymes 1000')])),
                ('fecha_alta', models.DateField(verbose_name='Fecha de Alta')),
                ('fecha_baja', models.DateField(verbose_name='Fecha de Baja')),
                ('coordenada_domicilio', models.CharField(max_length=50, verbose_name='Coordenadas domicilio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('email', models.EmailField(max_length=150)),
                ('legajo', models.IntegerField(verbose_name='Legajo')),
                ('categoria', models.IntegerField(choices=[(1, 'Vendedor'), (2, 'Supervisor')], verbose_name='Categoría')),
                ('comision', models.IntegerField(null=True, verbose_name='Comisión de Venta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
