# Generated by Django 3.2.18 on 2023-06-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_dni',
            field=models.IntegerField(verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='provincia',
            field=models.IntegerField(choices=[(1, 'Buenos Aires'), (2, 'Córdoba'), (3, 'Santa Fe'), (4, 'C.A.B.A.')], verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_dni',
            field=models.IntegerField(verbose_name='Tipo de documento'),
        ),
    ]
