# Generated by Django 3.2.18 on 2023-05-25 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='legajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.empleado', verbose_name='Vendedor asignado'),
        ),
    ]
