# Generated by Django 3.2.18 on 2023-05-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0002_auto_20230525_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='baja',
            field=models.BooleanField(default=False),
        ),
    ]
