# Generated by Django 3.2.18 on 2023-05-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0003_alter_cliente_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
