# Generated by Django 3.2.18 on 2023-05-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0004_alter_cliente_fecha_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='baja',
            field=models.BooleanField(default=0),
        ),
    ]
